const types = {
    REGISTER_LOADING: "REGISTER_LOADING",
    REGISTER_REQUEST: "USER_REGISTER_REQUEST",
    REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    REGISTER_FAILURE: "USER_REGISTER_FAILURE"
};

export default types;